version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:RAjQgBMKS90NW6ioLVZGy3iO1wjfqFDdlgY7pTmJFVA"

      - run:
          name: Add EC2 to known hosts
          command: |
            ssh-keyscan -H 52.67.130.181 >> ~/.ssh/known_hosts

      - run:
          name: Deploy to EC2
          command: |
            ssh ubuntu@52.67.130.181 "
              cd /var/www/html &&
              git pull origin main &&
              sudo systemctl restart nginx
            "

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - deploy

